various tweaks - move PATH declaration - move command check / trap call till after getopts - exit if mkdir(1) fails - remove empty line

diff --git a/fdomains b/fdomains
--- a/fdomains
+++ b/fdomains
@@ -17,6 +17,9 @@
 outfile=/tmp/${0##*/}.out
 tmpfile=/tmp/${0##*/}.tmp
 
+# include the python user script directory
+PATH=${PATH}:${HOME}/.local/bin
+
 die()
 {
 	echo "$1" 1>&2
@@ -35,14 +38,6 @@ cleanup()
 	done
 }
 
-# include the python user script directory
-PATH=${PATH}:${HOME}/.local/bin
-if ! command -v > /dev/null dnstwist; then
-	die "${0##*/}: dnstwist: command not found"
-fi
-
-trap "cleanup" 0 1 2 3 15
-
 while getopts "m:u" arg; do
 	case ${arg} in
 	m)	rcpt_to=${OPTARG}
@@ -54,13 +49,19 @@ done
 shift $((OPTIND - 1))
 [ "$#" -gt 0 ] || usage
 
+if ! command -v > /dev/null dnstwist; then
+	die "${0##*/}: dnstwist: command not found"
+fi
+
+trap "cleanup" 0 1 2 3 15
+
 domains="$*"
 for domain in ${domains}; do
 
 	archivedir=${HOME}/.${0##*/}
 	archive=${archivedir}/${domain}
 	if [ ! -d "${archivedir}" ]; then
-		mkdir -- ${archivedir}
+		mkdir -- ${archivedir} || exit 1
 	fi
 
 	# ignore $uflag if $archive does not exist
@@ -80,7 +81,6 @@ for domain in ${domains}; do
 
 	if [ "${uflag}" -eq 1 ]; then
 		sort ${outfile} ${archive} | uniq -u > ${tmpfile}
-
 		if [ -s "${tmpfile}" ]; then
 			cp -f -- ${outfile} ${archive}
 			cp -f -- ${tmpfile} ${outfile}
